#!/usr/bin/python3
# This scripts identifies tags and mac addresses of networking interfaces and configure them accordingly.
# Imports
import argparse
import json # to parse metadata json file
import os
import gi
gi.require_version("NM", "1.0")
from gi.repository import GLib, NM

# Classes

# Definition of class NIC including mac and tag
class NIC:
    def __init__(self,mac,tag):
        self.mac = mac.upper()
        self.interface = None
        self.tag = tag.upper()
        self.ip = None
        self.prefix = None
        self.gw = None
        self.nameserver = None

    def set_ip_settings(self,ip=None,prefix=None,gw=None,nameserver=None):
        self.ip = ip
        self.prefix = prefix
        self.gw = gw
        self.nameserver = nameserver

    def set_interface(self,interface):
        self.interface = interface

    def set_connection(self,connection_id):
        self.id = connection_id

    def get(self,all_settings=True):
       if all_settings:
           print(self.id,self.tag,self.interface,self.mac,self.ip,self.prefix,self.gw,self.nameserver)

# Parsing command line arguments.
# Two args are expected:
# * config
#    This is the config.json file including networking configuration for each device.
# * metadata
#    This is the meta_data.json file generated by the role device tagging when the VM boots.
# Samples of these files are available in this repository.

parser = argparse.ArgumentParser(description='Configure network interfaces according to config and metadata information',formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('config',help='The path where config.json file is located')
parser.add_argument('metadata',help='The path where meta_data.json file is located')
args = parser.parse_args()


# A list of nics
nics = [];

# Parsing devices from metadata file.
# Each pair of mac,tag will instantiated as a new nic

try:
  with open(args.metadata,'r') as input_file:
      input_data = json.load(input_file)
  devices = input_data["devices"]
  for device in devices:
    nics.append(NIC(device["mac"],device["tags"][0]))  
except IOError:
    print('Error opening input file')

# Parsing network configuration from file.
# Setting ip,prefix,gw and nameserver to each NIC instance.

try:
  with open(args.config,'r') as input_file:
      input_data = json.load(input_file)
  devices = input_data["devices"]
  for device in devices:
      for nic in nics:
          if device["tags"][0].upper() == nic.tag:
             nic.set_ip_settings(ip=device["ip"],prefix=device["prefix"],gw=device["gateway"],nameserver=device["nameserver"])
except IOError:
    print('Error opening input file')

# Mapping NIC instances and NetworkManager connections
# Modifying the NetworkManager connections accordingly

client = NM.Client.new(None)
devices = client.get_devices()
for device in devices:
    for nic in nics:
        try:
          if device.get_hw_address() == nic.mac:
            nic.set_interface(device.get_iface())
            nic.set_connection(device.get_active_connection().get_id())
            new_config = "nmcli con mod "+ "'" + nic.id + "'" + " ipv4.method manual ipv4.addresses " + nic.ip + "/" + nic.prefix + " ipv4.gateway " + nic.gw + " ipv4.dns " + nic.nameserver + " ipv6.method disabled"
            save_config = "nmcli con up " + "'" + nic.id + "'"
            os.system(new_config)
            os.system(save_config)
        except:
          print("An error occurred when setting the network configuration")
